### ISSUE TITLE
Godef not work 

### ISSUE THREAD

**Issue by fuyou001** [dgryski/vim-godef#11]
I follow the readme .
step1:go get -v code.google.com/p/rog-go/exp/cmd/godef
check:
➜  ~  which godef
/usr/local/bin/godef
➜  ~  ls -al /usr/local/bin/godef
lrwxr-xr-x  1 fuyou  admin  40 12  7 22:54 /usr/local/bin/godef -> /usr/local/Cellar/go/1.2/godef/bin/godef
➜  ~
step2: git clone https://github.com/dgryski/vim-godef ~/.vim/bundle/vim-godef
check:
➜  ~  ls -al ~/.vim/bundle/vim-godef
total 8
drwxr-xr-x   5 fuyou  staff   170 12  7 22:41 .
drwxr-xr-x  68 fuyou  staff  2312 12  7 23:10 ..
drwxr-xr-x  12 fuyou  staff   408 12  7 22:41 .git
-rw-r--r--   1 fuyou  staff   964 12  7 22:41 README.md
drwxr-xr-x   3 fuyou  staff   102 12  7 22:41 plugin

the gd is work ,but the godef is not work in vi

when i typed in vi set g:godef_split=0 
result in png
![qq20131207-20 2x](https://f.cloud.github.com/assets/685537/1698563/5dfd18ca-5f55-11e3-89e1-5a5c2bb0b835.png)

➜  Go-Redis git:(go1) ✗ echo $path
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /Users/fuyou/soft/java/apache-maven-3.0.5/bin /Users/fuyou/soft/java/apache-maven-3.0.5/bin
➜  Go-Redis git:(go1) ✗ which godef
/usr/local/bin/godef
➜  Go-Redis git:(go1) ✗
when in vi typeing godef ,result in pgn 
![qq20131207-21 2x](https://f.cloud.github.com/assets/685537/1698567/b8d1bd14-5f55-11e3-9847-f4cbeb49c702.png)

**Comment by dgryski** [comment]
Closing.  Please migrate to vim-go.
