### ISSUE TITLE
README unclear installation instructions

### ISSUE THREAD

**Issue by weberc2** [dgryski/vim-godef#23]
README says:

> `go get -v code.google.com/p/rog-go/exp/cmd/godef`
> `go install -v code.google.com/p/rog-go/exp/cmd/godef`
> To install this plugin, copy godef.vim to ~/.vim/plugin .

Maybe clarify that `godef.vim` is to be found in _this_ repo as opposed to the `code.google.com/...` repo? I know I was stumped on this one for several minutes, but perhaps I'm exceptionally out of it this morning.

**Comment by dgryski** [comment]
Closing.  Please migrate to vim-go.
