### ISSUE TITLE
split settings problem

### ISSUE THREAD

**Issue by xsank** [dgryski/vim-godef#31]
i use fatih/vim-go plugin,and i alse install the dgryski/vim-godef plugin.
now the :GoDef works ok,but the :gd always not found.
i alse add the following setting to the vimrc:
let g:go_def_mapping_enabled = 0
let g:godef_split = 6
but i still could not open the defination in the new window.
it just open in the current.

**Comment by dgryski** [comment]
Closing.  Please migrate to vim-go.
