### ISSUE TITLE
:call GodefUnderCursor()

### ISSUE THREAD

**Issue by zhaoguojie2010** [dgryski/vim-godef#34]
hi, I'm reading the docker source code.  One of the source file 

> github.com/docker/docker/cmd/docker/docker.go

 is as follow:

```
package main

import (
    "fmt"
    "os"
    "path/filepath"

    "github.com/Sirupsen/logrus"
    "github.com/docker/docker/api/client"
    "github.com/docker/docker/cli"
    "github.com/docker/docker/cli/cobraadaptor"
    cliflags "github.com/docker/docker/cli/flags"
    "github.com/docker/docker/cliconfig"
    "github.com/docker/docker/dockerversion"
    flag "github.com/docker/docker/pkg/mflag"
    "github.com/docker/docker/pkg/term"
    "github.com/docker/docker/utils"
)

var (
    commonFlags = cliflags.InitCommonFlags()
    clientFlags = initClientFlags(commonFlags)
    flHelp      = flag.Bool([]string{"h", "-help"}, false, "Print usage")
    flVersion   = flag.Bool([]string{"v", "-version"}, false, "Print version information and quit")
)

func main() {
    // Set terminal emulation based on platform as required.
    stdin, stdout, stderr := term.StdStreams()

    logrus.SetOutput(stderr)

    flag.Merge(flag.CommandLine, clientFlags.FlagSet, commonFlags.FlagSet)

    cobraAdaptor := cobraadaptor.NewCobraAdaptor(clientFlags)
    // .... some code
}
```

When i pressed 

> gd

 on `StdStreams()`, it showed 

> :call GodefUnderCursor()

. However, when i do the samething on `flag.Merge`, it worked perfectly. Any idea what's  happening? Is it possible that godef doesn't parse all the source code(FYI, docker has more than 590000 lines of code)?

**Comment by sgykfjsm** [comment]
I got the same issue. After reinstalling `github.com/rogpeppe/godef`, `gd` works fine again.
```
go get -v github.com/rogpeppe/godef
go install -v github.com/rogpeppe/godef```

**Comment by pirDOL** [comment]
sgykfjsm's method works for me. thx

**Comment by huahuapapa** [comment]
For anyone who reinstalled the `github.com/rogpeppe/godef` and still not work:
Try adding
`let g:godef_command="/the/full/path/to/my/gopath/bin/godef"`
to your .vimrc
It works for me. For more information, please checkout the issue #9

**Comment by huahuapapa** [comment]
I met the same question, and I found that if the package which the symbol defined in imports another package, which is not found in your GOPATH, then the godef can not parse correctly. No matter whether your symbol is in the missing package, the package imports missing package cannot parse correctly
I didn't make it sure in github.com/rogpeppe/godef, but I fix the problem by go get the missing package. Hope it helps.

**Comment by dgryski** [comment]
Closing.  Please migrate to vim-go.
