### ISSUE TITLE
GodefUnderCursor() warns about Current location list was changed

### ISSUE THREAD

**Issue by timesselens** [dgryski/vim-godef#35]
I'm using go 1.8, the GodefUnderCursor() command brings me to the correct file, but I'm getting the following warnings in vim. This is the case for both stdlib lookup as well as vendor lookups (which bring me to the correct file, only it doesn't jump to the correct line number)

```
Error detected while processing function GodefUnderCursor[10]..Godef:
line   21:
E926: Current location list was changed
```

**Comment by huyongde** [comment]
I also have this problem, I sloved it,  by updating  syntastic to newest code, and  let g:syntastic_check_on_open = 0   .  You can try this solution.

**Comment by yonggang985** [comment]
this function solved my same problem. @huyongde

**Comment by dgryski** [comment]
Closing.  Please migrate to vim-go.
